secrets:
    samba-admin-password:
        file: ./samba_admin.password

services:
    db:
        container_name: db
        image: ghcr.io/identicum/postgres:16
        restart: always
        pull_policy: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: postgrespwd
        volumes:
            - ./postgres-initdb/:/docker-entrypoint-initdb.d/

    idp:
        container_name: idp
        image: ghcr.io/identicum/keycloak:26.1
        restart: always
        ports:
            - 8080:8080
        environment:
            KC_BOOTSTRAP_ADMIN_USERNAME: admin
            KC_BOOTSTRAP_ADMIN_PASSWORD: admin
            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://db/keycloakdb
            KC_DB_USERNAME: keycloakusr
            KC_DB_PASSWORD: keycloakpwd
        depends_on:
            db:
                condition: service_healthy

    idp_setup:
        container_name: idp_setup
        image: ghcr.io/identicum/sherpa-deploy:latest
        pull_policy: always
        volumes:
            - ./terraform/:/usr/home/
        command: "./apply.sh"
        depends_on:
            idp:
                condition: service_healthy

    samba:
        container_name: samba
        hostname: sambadc1
        image: ghcr.io/identicum/samba-dc:latest
        pull_policy: always
        restart: always
        cap_add:
            - SYS_ADMIN
        environment:
            LOG_LEVEL: 3
            NETBIOS_NAME: sherpadc1
            REALM: "sherpa-demo.com"
            DOMAIN_ACTION: provision
        secrets:
            - samba-admin-password
        ports:
            - 389:389
            - 636:636
        volumes:
            - ./samba.conf:/etc/samba/conf.d/0global.conf
        networks:
            default:
                aliases:
                    - sherpadc1.sherpa-demo.com

    jwkporter:
        container_name: jwkporter
        image: ghcr.io/identicum/jwkporter:latest
        pull_policy: always
        restart: always
        ports:
            - "8000:8000"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db/jwkporterdb
            - SPRING_DATASOURCE_USERNAME=jwkporterusr
            - SPRING_DATASOURCE_PASSWORD=jwkporterpwd
            - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
            - IDP_ISSUER=http://idp:8080/realms/demo
            - IDP_JWK_ENDPOINT=http://idp:8080/realms/demo/protocol/openid-connect/certs
            - SWAGGER_TOKEN_ENDPOINT=http://idp:8080/realms/demo/protocol/openid-connect/token
            - APP_LOGGING_LEVEL=DEBUG
            - DB_LOGGING_LEVEL=INFO
        depends_on:
            db:
                condition: service_healthy
            idp_setup:
                condition: service_completed_successfully

    sherpa:
        container_name: sherpa
        image: ghcr.io/identicum/sherpa-deploy:latest
        pull_policy: always
        restart: always
        volumes:
            - ./:/usr/home/
        depends_on:
            idp_setup:
                condition: service_completed_successfully
            jwkporter:
                condition: service_started