secrets:
  samba-admin-password:
    file: ./samba_admin.password

services:
  sherpa:
    container_name: sherpa
    image: ghcr.io/identicum/sherpa-deploy:latest
    pull_policy: always
    restart: always
    volumes:
      - ../:/usr/home/
  samba:
    container_name: samba
    image: ghcr.io/identicum/samba-dc:latest
    pull_policy: always
    restart: always
    cap_add:
      - SYS_ADMIN
    environment:
      LOG_LEVEL: 3
      NETBIOS_NAME: sherpadc1
      REALM: "sherpa-demo.com"
      DOMAIN_ACTION: provision
    secrets:
      - samba-admin-password
    ports:
      - 389:389
      - 636:636
    volumes:
      - ./samba.conf:/etc/samba/conf.d/0global.conf
    networks:
      default:
        aliases:
          - sherpadc1.sherpa-demo.com
